Feat export filter mod
Kanaries/graphic-walker pull request #198
Opened 2023-10-25 07:28 UTC by islxyqwe

Add component to use filter outside the graphic walker.

usage: 
```
import { GraphicWalker, createFilterContext } from "@kanaries/graphic-walker";
const FilterContext = createFilterContext({
  SingleSelect: (props: {
    name: string;
    options: string[];
    value: string;
    onChange?: (v: string) => void;
  }) => {
    // return Your select component, such as <select>
  },
  MultiSelect: (props: {
    name: string;
    options: string[];
    value: string[];
    onChange?: (v: string[]) => void;
  }) => {
    // return Your Multi select component, such as <checkbox>
  },
  RangeSelect: (props: {
    name: string;
    domain: [number, number];
    value: [number, number];
    onChange?: (v: [number, number]) => void;
  }) => {
    // return Your Range component, such as <input type="range">
  },
  TemporalSelect: (props: {
    name: string;
    domain: [number, number];
    value: [number, number];
    onChange?: (v: [number, number]) => void;
  }) => {
    // return Your DatePicker component,  such as <input type="datetime-local">
  },
});

<FilterContext
  computation={graphicWalkerProps.computation}
  rawFields={graphicWalkerProps.rawFields}
  configs={[{ fid: "", mode: "range" }]}
>
  {(computationWithFilter, FilterComponents) => {
    return (
      <>
        <div className="page-header">{FilterComponents}</div>
        <div className="page-content">
          <GraphicWalker
            {...graphicWalkerProps}
            computation={computationWithFilter}
          />
        </div>
      </>
    );
  }}
</FilterContext>;
```

2023-10-26 03:11 UTC, islxyqwe commented
update: Add datasource to FilterContext

2023-10-27 08:45 UTC, ObservedObserver requested changes

2023-10-27 08:45 UTC, ObservedObserver commented on packages/graphic-walker/src/computation/index.ts
> +    const COUNT_ID = `count_${field}`;
do not use count, use unique. Count has other semantic meanings in graphic-walker.

Besides, I am not quite sure if the prefix will only be used in this function.

2023-10-30 23:05 UTC, ObservedObserver approved these changes

2023-10-30 23:06 UTC, ObservedObserver commented
@islxyqwe You can merged this PR if there is no conflict with the map-visualization PR.

2023-10-31 18:23 UTC, merged