feat: leaflet geojson support
Kanaries/graphic-walker pull request #94
Opened 2023-07-04 02:19 UTC by k6sdevbob

2023-08-08 06:12 UTC, islxyqwe requested changes

2023-08-08 06:12 UTC, islxyqwe commented on packages/graphic-walker/src/store/visualSpecStore.ts
> +        longitude: [],
visSpecDecoder should fill new fields with [] when reading old data

2023-08-08 06:12 UTC, islxyqwe commented on packages/graphic-walker/src/interfaces.ts
> +    geoRole?: IGeoRole;
should have some method to init this value/ change this value

2023-08-08 06:50 UTC, islxyqwe approved these changes

2023-08-10 09:59 UTC, ObservedObserver approved these changes

2023-08-10 10:00 UTC, merged